name: "Get JIRA User Story, Bug, or Task ID"
description: "Fetches ID of User Story, Bug, or Task from JIRA, including parent ID for subtasks. Outputs in lowercase."
author: "canhbk"
branding:
  icon: "tag"
  color: "blue"
inputs:
  issue_id:
    description: "The JIRA issue ID (can be a Subtask, User Story, Bug, or Task)"
    required: true
  jira_user:
    description: "The JIRA user (email)"
    required: true
  jira_api_token:
    description: "The JIRA API token"
    required: true
  jira_base_url:
    description: "The base URL for the JIRA instance"
    required: true

outputs:
  result_id:
    description: "The ID of the User Story associated with the subtask, or the ID of the User Story, Bug, or Task, in lowercase"
    value: ${{ steps.get_jira_issue_id.outputs.result_id }}
runs:
  using: "composite"
  steps:
    - name: Fetch Issue Details from JIRA
      id: get_jira_issue_id
      shell: bash
      run: |
        JIRA_USER=${{ inputs.jira_user }}
        JIRA_API_TOKEN=${{ inputs.jira_api_token }}
        JIRA_BASE_URL=${{ inputs.jira_base_url }}
        ISSUE_ID=${{ inputs.issue_id }}

        # Fetch the issue details
        RESPONSE=$(curl -s -u $JIRA_USER:$JIRA_API_TOKEN \
          -X GET -H "Content-Type: application/json" \
          "$JIRA_BASE_URL/rest/api/3/issue/$ISSUE_ID")

        # Extract the issue type
        ISSUE_TYPE=$(echo $RESPONSE | jq -r '.fields.issuetype.name' | tr '[:upper:]' '[:lower:]')

        # Extract the parent ID if it exists (for Subtasks)
        PARENT_ID=$(echo $RESPONSE | jq -r '.fields.parent.key')

        # Determine the result ID based on the issue type
        if [ "$ISSUE_TYPE" = "subtask" ]; then
          RESULT_ID=$PARENT_ID
        elif [ "$ISSUE_TYPE" = "story" ] || [ "$ISSUE_TYPE" = "bug" ] || [ "$ISSUE_TYPE" = "task" ]; then
          RESULT_ID=$ISSUE_ID
        else
          echo "Error: The issue ID $ISSUE_ID is not a Subtask, User Story, Bug, or Task. It is a $ISSUE_TYPE." >&2
          exit 1
        fi

        RESULT_ID=$(echo $RESULT_ID | tr '[:upper:]' '[:lower:]')

        # Set the output
        echo "result_id=$RESULT_ID" >> $GITHUB_OUTPUT
